version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/actions/resolve"
    schedule:
      interval: "monthly"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-tools:
        patterns: ["pytest*", "ruff", "mypy", "types-*", "pre-commit"]
